services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped 
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    volumes:
      - ./db.sql
    ports:
      - "5432:5432"

# docker-compose up -d
# docker-compose ps