services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped 
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./db.sql
    ports:
      - "5432:5432"

# docker-compose up -d
# docker-compose ps