name: dart_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  postgres: ^3.2.0
  shelf: ^1.4.1
  shelf_modular: ^2.1.0
  shelf_swagger_ui: ^1.0.0+2
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
